### ISSUE TITLE
Regular Updates

### ISSUE THREAD

**Issue by jesusvito** [acidjesuz/EPG#1]
Awesome work Jesuz! I thank you so much for your work... I use this EPG for my own m3u playlist. If its not much i would like to know the reason for regular updates to the file. I hope i dont bother with my question also i'd appreciate if you could add programming for the following channels. Thank you in advance!

Directv sports 1 y 2
FMH Movies
FMH Family
Axn
Axn White
TNT sports
Fox Sports Premium

**Comment by acidjesuz** [comment]
Hey Jesus,

First of all thank you for the kind words, second of all I'm so sorry I'm getting back to you so late but I was away from my home (computer) for almost three weeks.

I was just tired depending on other tv guides that would not show half of the channels that I use so I made my own EPG and made it public so other users can enjoy.

The reason the .xml (EPG file) file is getting updated every six hours because when the guide was getting updated every 24hrs some users reported that in between pulls from SD (schedules direct) the guide would not show up properly or not at all, so I tried updating every six hours and the issue went away. So that's the reason for the guide being updated every six hours.

As for the channels you ask, I'll take a look and I'll see what can be done about it.

Take Care Buddy.

aCiDjEsUs
    PwA

**Comment by jesusvito** [comment]
No worries at all! I'm incredibly thankful for your awesome work... I've been wondering if there's a way I could help you out (donation or asistance). Sorry for my English BTW is not my native tongue. Let me know if you have any telegram channel or contact info, but specially let me know how can I reward your work and encourage you to keep going :)

P.S. I'm Glad you are home now... Stay Safe and Healthy. Also, i would like to report that ESPN 1 and 2 for MX and ARG are missing (they werent missing a few days ago)

Your dearest friend... Jesusvito

**Comment by acidjesuz** [comment]
Jesus buddy no worries about any donations etc. I'm just glad people are using this guide. 

Actually everything is automated thru cron and two small scripts on my Ubuntu server, it pulls new guide from SD new EPG get's uploaded automatically to git  and it repeats every six hours.

About Spanish speaking channels, I don't speak Spanish so if the guide shows a wrong data I wouldn't know because I don't speak Spanish, all I can do is if I see missing data for that particular channel I can try to fix but like I said if it shows wrong guide I wouldn't know.

No worries you doing great with English, I can clearly understand you, besides English is not my native language either. 

I'll see about the channels.

Take Care,

aCiDjEsUs
PwA

**Comment by jesusvito** [comment]
You are most definitely amazing! I really appreciate it! Everything works flawlessly... Thank you in advance for looking into the missing channels! I'm here everyday, let me know if you change your mind regarding help in any way! Take care my friend.

**Comment by LSDsl** [comment]
Last update is very small. Just some channels 😭

**Comment by acidjesuz** [comment]
> Last update is very small. Just some channels sob

Just checked on my end and everything looks fine besides the usual missing channels. Maybe it was just a bad pull at night. I'll pull it right now and let me know if that helped. 

aCiDjEsUs
PwA

**Comment by LSDsl** [comment]
Last update also small (1.66 MB)

**Comment by LSDsl** [comment]
I think better check size before push file. ty
