### ISSUE TITLE
Sky Documentaries & Sky History/H2 Request

### ISSUE THREAD

**Issue by 99bobster99** [acidjesuz/EPG#2]
Awesome job keeping your guide.xml alive AcidJesuz! 

Just a small request, I noticed that the UK channels "Sky Documentaries" and "Sky History/H2" are missing, could you add these?

Also, I was wondering id it's possible to add some streaming service schedules (i.e. HBO Max, Hulu and Netflix)? This would be for EPG for an IPTV subscription. I don't think SD offers these, but thought I'd ask.

Thank you sir!

**Comment by acidjesuz** [comment]
Hey Bobster,

I just took a look at my EPG and I don't see those two channels. I might have to check again because I just took a glance before work. I'll check once again after work. If the channel is not on the list you would have to provide me with exact name of those channels as their appear on your service (I don't know what iptv provider you use) and I'll see if I can fix that for you. 

As for streaming services, I really never looked into it, I might have to..  if it's even possible or not. Will see. I might have some time next week to look into it.

aCiD

**Comment by 99bobster99** [comment]
Hey aCiD,

Yeah, these Sky channels are from the UK. Sorry, I should have mentioned that earlier. I read that Schedules Direct offers UK channels as well, within their membership. Not sure if these are channels you can combine into your guide.xml file or not. 

I found a UK website that has the schedule for this channel [https://tv24.co.uk/channel/sky-documentaries](url) I was thinking of maybe scraping the site for the data, that would be another option for me.

It's almost impossible to find any schedules for the streaming services, I imagine that this is by design, they don't want non-subscribers leeching their show information. With that said, I did find this one on Github, that had the Canadian streaming service Crave as an available channel [https://iptv-org.github.io/epg/guides/ca.xml](url). I'm not sure where these guys get their schedule content, it doesn't look like Schedules Direct?

That would be great if you could have a look, whenever you have time.


Cheers!
Bobster

**Comment by acidjesuz** [comment]
Hey Bobster,

Let's just concentrate on UK channels first and then will go from there.

I don't think it should  be a problem to add that channel/s, but like I asked in previous post I would have to know the exact name of that channel/s as it shows in you service. Exact spelling, exactly how it appears in your EPG. 

Is it just Sky Documentaries and Sky History, Sky H2? or is the SKY spelled all capital etc. You know what I mean? I think You do :)

aCiD

**Comment by 99bobster99** [comment]
Hey aCiD,

Sounds good! :)

The (2) UK channels are showing like this below, from my IPTV provider;

- Sky Documentaries

- Sky History 2

Please let me know what you find out. Thank you aCiD!

Bobster

**Comment by acidjesuz** [comment]
Hey Bobster,
I just added those two channels, did a new pull and a new push to git. 
Because I don't have those channels I don't know if the EPG got populated with info or not.

Can you please check and let me know, if you don't see it at first maybe clear your epg and then try to pull it again.

aCiD

**Comment by 99bobster99** [comment]
Hey aCiD,

They work perfectly! :)  You are the best sir, thank you for adding those channels!

Can you work the same magic on any of the streaming sites I mentioned (HBO Max, Hulu, Netflix, Showtime)?

Bobster

**Comment by acidjesuz** [comment]
Hey Bobster,

So I was going over what can be done about EPG for the streaming providers and I came to a conclusion that it's kinda not possible for streaming services to have a guide.

Because You as a user you choose what you want to watch, it's not like a constant channel.  I

t's streaming what you want to watch, so if you know already what yo want to watch why would you need a guide for that?? am I right or am I too tired after work lol :)

I don't know about Hulu but I know Amazon Prime, Netflix they don't have a channels it's only streaming services you go on the list pick a show you want to watch and it plays.  

aCiD

**Comment by 99bobster99** [comment]
Hey aCiD,

Most IPTV providers, offer scheduled programming for multiple streaming sites. My provider offers these, each channel having scheduled programming;

- HBO Max 1, HBO Max 2, HBO Max 3, and HBO Max 4  

- Hulu 1, Hulu 2, Hulu 3, and Hulu 4  

- same as above, but for Showtime. They also have (4) channels for something called "Home Box Office", which are playing schedules 2022 movies. Same, thing though, I can't find any EPG for any of these channels. I'm not sure where the IPTV provider sources these channels, but I believe they are similar to how these (4) channels are offered by Crave (a Canadian streaming service) -> [https://www.crave.ca/en/live?tab=schedule](url)

I'm sure a similar schedule exists for HBO Max, Hulu and Showtime it's just where. I'm considering using "Tempest EPG Generator" [https://github.com/K-vanc/Tempest-EPG-Generator](url) to scrape the Crave schedule website. But it seems that the US keeps their schedules hidden away somewhere.

Bobster
