### ISSUE TITLE
EPG for PIX 11 Pulling Wrong Data

### ISSUE THREAD

**Issue by boeder8** [acidjesuz/EPG#6]
Hello aCiD,

Hope you're well buddy.

It seems like the epg for "PIX 11" (CW New York) is wrong, the data pulled is for CW Seattle (KSTW).

Also the logo color for PIX 11 looks to be off, is it possible it can be changed? (I'm a nit picker lol and the current color is too light for the theme of my player) this is the better logo: 
https://i.imgur.com/URqp3lW.png

Alternatively, you can perhaps add "CW New York" to the guide if you can find it.

Finally, a tough request, im looking for the epg for a US channel called DeFiance Media, I can't find it anywhere and it's driving me mad! It's available on Sling and Local Now I believe. This is their website: http://defiance.media and their logo: https://i.imgur.com/UjT6wyB.png

Thanks for maintaining the epg and the recent updates!

**Comment by acidjesuz** [comment]
Hey Boeder,

I think the feed just changed from CW Seattle to CW New York. I'll take a look after work. I know it was Seattle feed because that's the only channel I'm pulling from Comcast-Tacom and that's the only channel in my .chl and .ren files. Will see what can be done about that.

As for the logos, I have no control over that, sorry my friend. But if you use Tivimate by any chance there's an option to have the logos from the Playlist, Logos from EPG or Prefer logos from Folder. I use the second option "Logos fro EPG" and logos looks pretty nice. Or you can use the third option and have the logos stored somewhere in the folder and pull logos from that folder.

I'll see about that DeFiance Media but I don't promise anything :) I'll have some time tonight after work so I'll see what can be done about that channel.

Take Care and have an awesome day/evening/night where ever you are in the world :)

aCiD

**Comment by boeder8** [comment]
Hi again,

Great. Hope you're able to pull the correct data for PIX 11 and/or add CW New York and if you find DeFiance that'll be awesome too, but no pressure it's a tough find apparently.

I'm using Tivimate and logos are set on EPG which is good except when the odd logo needs changing lol. I hope Tivimate add the feature of individually customizing logos 

Big thanks! And have a glorious weekend!

**Comment by boeder8** [comment]
I can confirm that the PIX 11 is now pulling the correct data! Thanks!
